### ISSUE TITLE
Error trying to convert [s.dut.tile[0].element.fu[0], s.dut.tile[0].element.fu[1]] into RTLIR:

### ISSUE THREAD

**Issue by E24066331** [pnnl/OpenCGRA#2]
Getting errors when running CGRARTL_test.py with py.test under the cgra/translate directory:

E   pymtl3.passes.rtlir.errors.RTLIRConversionError:
E   In file /home/e24066331/venv/lib/python3.6/site-packages/pymtl3/passes/rtlir/rtype/RTLIRType.py, Line 481, Method _handle_Array:
E   Error trying to convert [s.dut.tile[0].element.fu[0], s.dut.tile[0].element.fu[1]] into RTLIR:
E   - all elements of array [s.dut.tile[0].element.fu[0], s.dut.tile[0].element.fu[1]] must have the same type Component!
E     f'all elements of array {obj} must have the same type {ref_type}!'

It might have to do with the FuList but still not sure where the problem is. 
I cloned the whole repo down on my computer without any modifying.

**Comment by tancheng** [comment]
Hi, did you install the specific version of PyMTL3 I indicated inside the README, which is `pip install git+https://github.com/cornell-brg/pymtl3.git@76e1ef87b2d7b6202abebea5b507398505910948#egg=pymtl3`.

**Comment by E24066331** [comment]
Hi, yes I followed the installation procedure in README.  In my pip list it shows pymtl3 0.5.5.

**Comment by tancheng** [comment]
How about upgrade python to 3.7 and try again?

**Comment by E24066331** [comment]
I just upgraded it but still producing the same error.

E   pymtl3.passes.rtlir.errors.RTLIRConversionError:
E   In file /home/e24066331/venv2/lib/python3.7/site-packages/pymtl3/passes/rtlir/rtype/RTLIRType.py, Line 481, Method _handle_Array:
E   Error trying to convert [s.dut.tile[0].element.fu[0], s.dut.tile[0].element.fu[1]] into RTLIR:
E   - all elements of array [s.dut.tile[0].element.fu[0], s.dut.tile[0].element.fu[1]] must have the same type Component!
E     f'all elements of array {obj} must have the same type {ref_type}!'

I also ran TileRTL_test.py under tile/translate and get this:

../../venv2/lib/python3.7/site-packages/pymtl3/stdlib/test/test_sinks.py:49: in up_sink_count
    raise Exception( s.error_msg )
E   Exception: Test sink s.sink_out[3] received WRONG message!
E   Expected : 00000009.1.0
E   Received : 00000000.0.0

**Comment by tancheng** [comment]
You can check about the configuration and the library version used in the build (https://travis-ci.com/github/pnnl/OpenCGRA/builds/208619002). Make sure your local building match that. If there is still error, you can use [repl.it](https://repl.it/~) to share with me? Since I cannot reproduce it locally.

**Comment by tancheng** [comment]
Hi, I think I found the problem. PyMTL3 is migrated into a new organization on github. So something wrong with the specific branch that OpenCGRA relies on. I upload my local version of PyMTL3 and you can pip install it (`pip install git+https://github.com/tancheng/pymtl3.git`) to replace the old one. Please have a try.

**Comment by E24066331** [comment]
Wow It works! Thank you very much! Appreciate your time and effort in helping me!
