### ISSUE TITLE
AURORA's code has not been open-sourced?

### ISSUE THREAD

**Issue by segmentKOBE** [pnnl/OpenCGRA#8]
Hi Tancheng,

I'd like to have a look on the code of AURORA, but I did not find it in OpenCGRA or other repositories, so I think it has not been open-sourced yet, right?

And will it be an open source project in github in the future? Thank you Tancheng!

Best Regards.

**Comment by tancheng** [comment]
Hi, AURORA relies on multiple third-party tools and is not supposed to be open-sourced. Sorry about that. You are still welcome to use OpenCGRA as a template to collect the HW area/power/timing of the basic FU/tile and construct your own CGRA or estimate its HW stats. Thanks for your interest anyways.

**Comment by segmentKOBE** [comment]
> Hi, AURORA relies on multiple third-party tools and is not supposed to be open-sourced. Sorry about that. You are still welcome to use OpenCGRA as a template to collect the HW area/power/timing of the basic FU/tile and construct your own CGRA or estimate its HW stats. Thanks for your interest anyways.

Thanks for your replying !! It is unlucky because there are so few powerful analysis tools in CGRA front-end like AURORA hahaha
